## Name - Rishabh Dwivedi
### Section - C3  Roll no. - 45

In [ ]:
import pandas as pd
import numpy as np
data = pd.read_csv('/content/enjoy - enjoy.csv')
data.head()

     Sky AirTemp Humidity    Wind Water Forecast EnjoySport
0  Sunny    Warm   Normal  Strong  Warm     Same        Yes
1  Sunny    Warm     High  Strong  Warm     Same        Yes
2  Rainy    Cold     High  Strong  Warm   Change         No
3  Sunny    Warm     High  Strong  Cool   Change        Yes
4  Sunny    Cold   Normal    Weak  Warm     Same         No

### Basic Data Exploration

In [ ]:
# Display basic information about the DataFrame
display(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Sky         10 non-null     object
 1   AirTemp     10 non-null     object
 2   Humidity    10 non-null     object
 3   Wind        10 non-null     object
 4   Water       10 non-null     object
 5   Forecast    10 non-null     object
 6   EnjoySport  10 non-null     object
dtypes: object(7)
memory usage: 692.0+ bytes

None

In [ ]:
# Display descriptive statistics
display(data.describe(include='all'))

          Sky AirTemp Humidity    Wind Water Forecast EnjoySport
count      10      10       10      10    10       10         10
unique      3       2        2       2     2        2          2
top     Sunny    Warm   Normal  Strong  Warm     Same        Yes
freq        7       8        5       5     6        7          6

In [ ]:
# Check for missing values
display(data.isnull().sum())

Sky           0
AirTemp       0
Humidity      0
Wind          0
Water         0
Forecast      0
EnjoySport    0
dtype: int64

In [ ]:
x = data

In [ ]:
# Separate features (X) and target (y)
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

In [ ]:
def find_s(X,y):
    hypo= None
    print("Intial Hypothesis:",hypo)
    for i in range(len(X)):
        if y[i] == "Yes":
            if hypo is None:
                hypo=X.iloc[i].values.copy()
            else:
                for j in range(len(hypo)):
                    if hypo[j] != X.iloc[i].values[j]:
                        hypo[j]="?"
        print(f"\nAfter Training Example {i+1}")
        print(hypo)
    return hypo
final_hypo=find_s(X,y)
print("\nFinal Hypothesis",final_hypo)

Intial Hypothesis: None

After Training Example 1
['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']

After Training Example 2
['Sunny' 'Warm' '?' 'Strong' 'Warm' 'Same']

After Training Example 3
['Sunny' 'Warm' '?' 'Strong' 'Warm' 'Same']

After Training Example 4
['Sunny' 'Warm' '?' 'Strong' '?' '?']

After Training Example 5
['Sunny' 'Warm' '?' 'Strong' '?' '?']

After Training Example 6
['Sunny' 'Warm' '?' 'Strong' '?' '?']

After Training Example 7
['Sunny' 'Warm' '?' '?' '?' '?']

After Training Example 8
['Sunny' 'Warm' '?' '?' '?' '?']

After Training Example 9
['Sunny' 'Warm' '?' '?' '?' '?']

After Training Example 10
['Sunny' 'Warm' '?' '?' '?' '?']

Final Hypothesis ['Sunny' 'Warm' '?' '?' '?' '?']

In [ ]:
import copy
def candidate_elimination(concepts, target):
  specific = concepts.iloc[0].values.copy()
  general = [["?" for _ in range(len(specific))]]

  print("Intial Specific Hypothesis:",specific)
  print("Intial General Hypothesis:",general)


  for i in range(len(concepts)):
    h = concepts.iloc[i].values
    current_target = target.iloc[i]

    if current_target == "Yes":
      for x in range(len(specific)):
        if h[x] != specific[x]:
          specific[x] = "?"

    else:
      for x in range(len(specific)):
        if h[x] != specific[x]:
          general.append(["?" if j != x else specific[x] for j in range(len(specific))])


    print(f"\nExample {i+1}")
    print("Specific =",specific)
    print("General =",general)

  return specific,general
S,G = candidate_elimination(X,y)
print("\nInitial Specific boundary")
print(S)
print("Final General Hypothesis:")
print(G)

Intial Specific Hypothesis: ['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']
Intial General Hypothesis: [['?', '?', '?', '?', '?', '?']]

Example 1
Specific = ['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']
General = [['?', '?', '?', '?', '?', '?']]

Example 2
Specific = ['Sunny' 'Warm' '?' 'Strong' 'Warm' 'Same']
General = [['?', '?', '?', '?', '?', '?']]

Example 3
Specific = ['Sunny' 'Warm' '?' 'Strong' 'Warm' 'Same']
General = [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same']]

Example 4
Specific = ['Sunny' 'Warm' '?' 'Strong' '?' '?']
General = [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same']]

Example 5
Specific = ['Sunny' 'Warm' '?' 'Strong' '?' '?']
General = [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

Example 6
Specific = ['Sunny' 'Warm' '?' 'Strong' '?' '?']
General = [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

Example 7
Specific = ['Sunny' 'Warm' '?' '?' '?' '?']
General = [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

Example 8
Specific = ['Sunny' 'Warm' '?' '?' '?' '?']
General = [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

Example 9
Specific = ['Sunny' 'Warm' '?' '?' '?' '?']
General = [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

Example 10
Specific = ['Sunny' 'Warm' '?' '?' '?' '?']
General = [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

Initial Specific boundary
['Sunny' 'Warm' '?' '?' '?' '?']
Final General Hypothesis:
[['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]